version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - TZ=Asia/Ho_Chi_Minh
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cooking
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./cooking.sql:/docker-entrypoint-initdb.d/cooking.sql:ro
volumes:
  db_data: 